# Generated by Django 5.2 on 2025-04-07 17:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25, verbose_name='رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='InsoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insole_model', models.CharField(max_length=15, verbose_name='جنس داخل')),
            ],
        ),
        migrations.CreateModel(
            name='OpenClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_close', models.CharField(max_length=20, verbose_name='نحوه باز و بسته شدن')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/gallery', verbose_name='گالری')),
                ('alt_text', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=25, verbose_name='سایز')),
            ],
        ),
        migrations.CreateModel(
            name='SoleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sole_material', models.CharField(max_length=15, verbose_name='جنس کفی')),
            ],
        ),
        migrations.CreateModel(
            name='TopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_material', models.CharField(max_length=15, verbose_name='جنس رویه')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام محصول')),
                ('air_circulation', models.BooleanField(default=False, verbose_name='گردش هوا')),
                ('waterproof', models.BooleanField(default=False, verbose_name='ضد اب')),
                ('capsule_in_heel', models.BooleanField(default=False, verbose_name='کپسول فشار در قسمت پاشنه')),
                ('capsule_in_claw', models.BooleanField(default=False, verbose_name='کپسول فشار در قسمت پنجه ')),
                ('main_image', models.ImageField(upload_to='product/main', verbose_name='عکس اصلی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف (%)')),
                ('category', models.ManyToManyField(to='product.category')),
                ('color', models.ManyToManyField(related_name='product', to='product.color', verbose_name='رنگ')),
                ('insole_model', models.ManyToManyField(related_name='product', to='product.insolemodel', verbose_name='جنس کفی')),
                ('open_close', models.ManyToManyField(related_name='product', to='product.openclose', verbose_name='نحوه باز و بسته شدن')),
                ('gallery_image', models.ManyToManyField(related_name='product', to='product.productgallery', verbose_name='گالری')),
                ('size', models.ManyToManyField(related_name='product', to='product.size', verbose_name='سایز')),
                ('sole_material', models.ManyToManyField(related_name='product', to='product.solematerial', verbose_name='جنس زیره')),
                ('top_material', models.ManyToManyField(related_name='product', to='product.topmaterial', verbose_name='جنس رویه')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('body', models.TextField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
