# Generated by Django 5.2 on 2025-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_first_name_address_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
